// examples/example-react/app/page.tsx
'use client';

import { useState } from 'react';
import { CslTable, CslModal } from '../components/LitWrappers';

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const tableColumns = [
    { key: 'id', label: 'ID' },
    { key: 'name', label: 'Name' },
    { key: 'email', label: 'Email' },
  ];

  const tableData = [
    { id: 1, name: 'Alice', email: 'alice@example.com' },
    { id: 2, name: 'Bob', email: 'bob@example.com' },
    { id: 3, name: 'Charlie', email: 'charlie@example.com' },
    { id: 4, name: 'David', email: 'david@example.com' },
    { id: 5, name: 'Eve', email: 'eve@example.com' },
  ];

  return (
    <main className="flex min-h-screen flex-col items-center p-24">
      <h1 className="text-4xl font-bold mb-8">Next.js with Cross-Stack Lib</h1>

      <div className="w-full max-w-4xl mb-16">
        <h2 className="text-2xl font-semibold mb-4">Table Component</h2>
        <CslTable columns={tableColumns} data={tableData} pageSize={5}></CslTable>
      </div>

      <div>
        <h2 className="text-2xl font-semibold mb-4">Modal Component</h2>
        <button
          onClick={() => setIsModalOpen(true)}
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        >
          Open Modal
        </button>
        <CslModal open={isModalOpen} onClose={() => setIsModalOpen(false)}>
          <div slot="header">Modal Header</div>
          <div slot="body">This is a modal inside a Next.js app!</div>
          <div slot="footer" style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <button onClick={() => setIsModalOpen(false)} className="px-4 py-2 bg-gray-300 rounded hover:bg-gray-400">
              Close
            </button>
          </div>
        </CslModal>
      </div>
    </main>
  );
}

// examples/example-angular/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';

// Import the custom elements to register them
import 'cross-stack-lib/csl-table';
import 'cross-stack-lib/csl-modal';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  template: `
    <h1>Angular with Cross-Stack Lib</h1>

    <div style="margin-bottom: 40px;">
      <h2>Table Component</h2>
      <csl-table [columns]="tableColumnsJson" [data]="tableDataJson" [pageSize]="3"></csl-table>
    </div>

    <div>
      <h2>Modal Component</h2>
      <button (click)="isModalOpen = true" style="padding: 8px 16px; background-color: #a6120d; color: white; border: none; border-radius: 4px; cursor: pointer;">
        Open Modal
      </button>
      <csl-modal [open]="isModalOpen" (close)="isModalOpen = false">
        <div slot="header">Angular Modal Header</div>
        <div slot="body">
          <p>This is a modal inside an Angular app!</p>
        </div>
        <div slot="footer" style="display: flex; justify-content: flex-end; gap: 10px;">
          <button (click)="isModalOpen = false" style="padding: 8px 16px; background-color: #ccc; border: none; border-radius: 4px; cursor: pointer;">
            Close
          </button>
        </div>
      </csl-modal>
    </div>
  `,
  styleUrl: './app.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA] // Allow custom elements
})
export class AppComponent {
  title = 'example-angular';
  isModalOpen = false;

  tableColumns = [
    { key: 'id', label: 'ID' },
    { key: 'name', label: 'Name' },
    { key: 'email', label: 'Email' },
  ];

  tableData = [
    { id: 1, name: 'Angular User 1', email: 'angular1@example.com' },
    { id: 2, name: 'Angular User 2', email: 'angular2@example.com' },
    { id: 3, name: 'Angular User 3', email: 'angular3@example.com' },
    { id: 4, name: 'Angular User 4', email: 'angular4@example.com' },
    { id: 5, name: 'Angular User 5', email: 'angular5@example.com' },
  ];

  get tableColumnsJson() {
    return JSON.stringify(this.tableColumns);
  }

  get tableDataJson() {
    return JSON.stringify(this.tableData);
  }
}
